// unlink_tracer.c
#include <bpf/libbpf.h>
#include <signal.h>
#include <stdio.h>
#include <sys/utsname.h>
#include <unistd.h>

#include "unlink_tracer.h"
#include "unlink_tracer.skel.h" // Generated by bpftool

static volatile sig_atomic_t stop;

static void sig_int(int signo) { stop = 1; }

static int handle_event(void *ctx, void *data, size_t sz) {
    const struct event *e = data;
    char full_path[MAX_PATH_LEN + MAX_FILENAME_LEN];
    memset(full_path, 0, sizeof(full_path));

    // Combine the directory path and filename in user-space
    snprintf(full_path, sizeof(full_path), "%s/%s", e->dir_path, e->filename);

    printf("%-8d %-16s %s\n", e->pid, e->process_name, full_path);
    return 0;
}

int main(void) {
    struct unlink_tracer_bpf *skel;
    struct ring_buffer *rb;
    int err;

    struct utsname u;
    uname(&u);
    printf("Kernel: %s\n", u.release);
    printf("Tracing file unlink events... Press Ctrl-C to stop.\n");

    skel = unlink_tracer_bpf__open();
    if (!skel) {
        fprintf(stderr, "Failed to open BPF skeleton\n");
        return 1;
    }

    err = unlink_tracer_bpf__load(skel);
    if (err) {
        fprintf(stderr, "Failed to load BPF skeleton\n");
        goto cleanup;
    }

    err = unlink_tracer_bpf__attach(skel);
    if (err) {
        fprintf(stderr, "Failed to attach BPF skeleton: %d\n", err);
        fprintf(stderr, "Did you enable the BPF LSM? (e.g., lsm=bpf,...)\n");
        goto cleanup;
    }

    rb = ring_buffer__new(bpf_map__fd(skel->maps.events), handle_event, NULL,
                          NULL);
    if (!rb) {
        err = -1;
        fprintf(stderr, "Failed to create ring buffer\n");
        goto cleanup;
    }

    signal(SIGINT, sig_int);
    signal(SIGTERM, sig_int);

    printf("%-8s %-16s %s\n", "PID", "COMMAND", "PATH");

    while (!stop) {
        err = ring_buffer__poll(rb, 100 /* timeout, ms */);
        if (err == -EINTR) {
            err = 0;
            break;
        }
        if (err < 0) {
            printf("Error polling ring buffer: %d\n", err);
            break;
        }
    }

cleanup:
    ring_buffer__free(rb);
    unlink_tracer_bpf__destroy(skel);
    return err < 0 ? -err : 0;
}
